export enum Namespaces {
    CHAT_MESSAGES = 'chatMessages',
    WAITING_ROOM = 'waitingRoom',
    GAME_STATS = 'gameStats',
    GAME = 'game',
    GLOBAL_NAMESPACE = 'global',
}

export enum Events {
    CREATE_ROOM = 'createRoom',
    DELETE_ROOM = 'deleteRoom',
    JOIN_ROOM = 'joinRoom',
    PLAYER_LEFT = 'playerLeft',
    PLAYER_JOINED = 'playerJoined',
    CONNECTION = 'connection',
    CHAT_MESSAGE = 'chatMessage',
    WAITING_ROOM_NOTIFICATION = 'waitingRoomNotification',
    QCM_STATS = 'qcmStats',
    QRL_STATS = 'qrlStats',
    QRL_ANSWER = 'qrlAnswer',
    QRL_GRADE = 'qrlGrade',
    SEND_QRL_ANSWER = 'sendQrlAnswer',
    FINAL_ANSWER = 'finalAnswer',
    BONUS = 'bonus',
    BONUS_GIVEN = 'bonusGiven',
    NEXT_QUESTION = 'nextQuestion',
    ABORT_GAME = 'abortGame',
    END_GAME = 'endGame',
    CLEANUP_GAME = 'cleanupGame',
    KICK_PLAYER = 'kickPlayer',
    GET_PLAYERS = 'getPlayers',
    LEAVE_ROOM = 'leaveRoom',
    LOCK_ROOM = 'lockRoom',
    UNLOCK_ROOM = 'unlockRoom',
    SET_PLAYER_NAME = 'playerName',
    GET_GAME_ID = 'getGameId',
    GET_PLAYER_PROFILE = 'playerProfile',
    START_GAME = 'startGame',
    NAME_NOT_AVAILABLE = 'nameNotAvailable',
    BANNED_NAME = 'bannedName',
    GAME_RESULTS = 'gameResults',
    CHAT_HISTORY = 'chatHistory',
    START_TIMER = 'startTimer',
    STOP_TIMER = 'stopTimer',
    PAUSE_TIMER = 'pauseTimer',
    PANIC_MODE = 'panicMode',
    PANIC_MODE_OFF = 'panicModeOff',
    SHOW_RESULTS = 'showResults',
    UPDATE_CHART = 'updateChart',
    UPDATE_PLAYER = 'updateScore',
    CONFIRM_ANSWERS = 'confirmAnswers',
    NOTIFY_QRL_INPUT = 'notifyQRLInput',
    EXCLUDE_FROM_CHAT = 'excludeFromChat',
    INCLUDE_IN_CHAT = 'includeInChat',
    ABANDON_GAME = 'abandonGame',
}

export const LOBBY = '0';
